name: ioos-metrics
channels:
  - conda-forge
dependencies:
  - python=3.11
  - bs4
  - fiscalyear
  - geopandas>=0.13.2
  - jupyter
  - jinja2
  - lxml
  - owslib
  - pandas
  - pip
  - pip:
      - pdbufr
  - eccodes
  - requests
  - suds