name: ioos-metrics
channels:
  - conda-forge
dependencies:
  - python=3.11
  - bs4
  - eccodes
  - fiscalyear
  - geopandas>=0.13.2
  - jinja2
  - jupyter
  - lxml
  - owslib
  - pandas
  - pdbufr
  - requests
  - suds
