name: Collect quarterly metrics

on:
  push:
     branches: 
       - main
     paths:
       - '.github/workflows/metrics.yml'
       - 'gts_metrics.py'
       - 'btn_metrics.py'
  schedule:
    - cron: "0 12 5 * *"

jobs:
  scheduled:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: false

      - name: Install conda environment
        shell: bash -l {0}
        run: |
          micromamba create --file environment.yml   

      - name: echo secrets into a file
        shell: bash -l {0}
        env:
          CDMO_KEY : ${{ secrets.CDMO_KEY }}
          CDMO_NAME : ${{ secrets.CDMO_NAME }}
        run: |
          echo "CDMO_NAME = \"${CDMO_NAME}\"" > config.py
          echo "CDMO_KEY = \"${CDMO_KEY}\"" >> config.py


      - name: Collect quarterly GTS and BTN metrics
        shell: bash -l {0}
        run: |
          micromamba activate ioos-btn
          python btn_metrics.py

      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
