name: Collect quarterly metrics

on:
  push:
     branches: 
       - main
     paths:
       - '.github/workflows/**'
       - 'ioos_metrics.py'
  workflow_dispatch:
  schedule:
    - cron: "0 12 5 1,4,7,10 *"

jobs:
  scheduled:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
          conda-channels: conda-forge

      - name: Build environment
        shell: bash -l {0}
        run: |
          conda env create -f environment.yml

      - name: Collect quarterly metrics
        run: |
          source activate ioos-btn
          python ioos_metrics.py

      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
